jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: 1mh0rJDSOCmZiJRw4LRCBoe/+rxrdXheBHmsEe1Sp23XiJok4mDbgHKEbzPJ7oshk6L1Lsc6JJpT3DqUIvt6tgkXDbjoPn6uu1rFx4szfTpVUx1roCbn0aj73/kMeCdJzWYgdliUnQzt25MKhtfOX9cQ8nZ3SokvTCqxZMa6mEI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: onlinetoken
  # 验证码
  code-key: xxg-code-key
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000